package Interfaz;

import Logica.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MostrarLibros extends javax.swing.JFrame {

    AdministrarLibro ali = new AdministrarLibro();
    AdministrarCategoria ac = new AdministrarCategoria();
    AdministrarAutor aa = new AdministrarAutor();
    AdministrarIdioma ai = new AdministrarIdioma();
    Tablas tabla = new Tablas();

    /**
     * Creates new form MostrarEditoriales
     */
    public MostrarLibros() {
        initComponents();
        setLocationRelativeTo(null);
        jTLibros.setModel(mostrarLibros());
        tabla.resizeColumnWidth(jTLibros);
    }

    /**
     * Llena la tabla que muestra libros disponibles en la biblioteca
     */
    public DefaultTableModel mostrarLibros() {
        List<Libro> libros2 = new ArrayList<Libro>();
        DefaultTableModel res = new DefaultTableModel();
        res.addColumn("ID");
        res.addColumn("Ejemplares");
        res.addColumn("Categoria");
        res.addColumn("Autor");
        res.addColumn("Titulo");
        res.addColumn("Descripción");
        res.addColumn("edicion");
        res.addColumn("Idioma");

        ali.mostrarLibro();
        libros2 = ali.mostrarLibro();

        int i = 0;
        for (Libro l : libros2) {
            res.addRow(new Object[]{});
            res.setValueAt(l.getId(), i, 0);
            res.setValueAt(ali.ObtenerEjemplares(l.getId()), i, 1);
            res.setValueAt(ac.obtenerCat(l.getIdCategoria()), i, 2);
            res.setValueAt(aa.ObtenerAut(l.getIdAutor()), i, 3);
            res.setValueAt(l.getTitulo(), i, 4);
            res.setValueAt(l.getDescripcion(), i, 5);
            res.setValueAt(l.getEdicion(), i, 6);
            res.setValueAt(ai.ObtenerIdio(l.getIdioma()), i, 7);
            i++;
        }
        return res;
    }

    /**
     * Llena la tabla que muestra libros de la busqueda
     */
    public DefaultTableModel buscarLibros(String n) {
        List<Libro> libros2 = new ArrayList<Libro>();
        DefaultTableModel res = new DefaultTableModel();
        res.addColumn("ID");
        res.addColumn("Ejemplares");
        res.addColumn("Categoria");
        res.addColumn("Autor");
        res.addColumn("Titulo");
        res.addColumn("Descripción");
        res.addColumn("edicion");
        res.addColumn("Idioma");

        ali.mostrarLibro();
        libros2 = ali.buscarLibro(n);

        int i = 0;
        for (Libro l : libros2) {
            res.addRow(new Object[]{});
            res.setValueAt(l.getId(), i, 0);
            res.setValueAt(ali.ObtenerEjemplares(l.getId()), i, 1);
            res.setValueAt(ac.obtenerCat(l.getIdCategoria()), i, 2);
            res.setValueAt(aa.ObtenerAut(l.getIdAutor()), i, 3);
            res.setValueAt(l.getTitulo(), i, 4);
            res.setValueAt(l.getDescripcion(), i, 5);
            res.setValueAt(l.getEdicion(), i, 6);
            res.setValueAt(ai.ObtenerIdio(l.getIdioma()), i, 7);
            i++;
        }
        return res;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFBuscarLibro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTLibros = new javax.swing.JTable();
        jBBuscar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBEjemplar = new javax.swing.JButton();
        jBAgregar = new javax.swing.JButton();
        jLAtras = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel de libros");
        setResizable(false);

        jLabel6.setBackground(new java.awt.Color(204, 255, 204));
        jLabel6.setFont(new java.awt.Font("Consolas", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Libros");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Libros disponibles"));

        jLabel1.setText("Buscar por título:");

        jTFBuscarLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFBuscarLibroKeyPressed(evt);
            }
        });

        jTLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTLibros);

        jBBuscar.setText("Actualizar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBEjemplar.setText("Ejemplar");
        jBEjemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEjemplarActionPerformed(evt);
            }
        });

        jBAgregar.setText("Agregar");
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTFBuscarLibro)
                        .addGap(18, 18, 18)
                        .addComponent(jBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jBEjemplar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(jBModificar)
                        .addGap(18, 18, 18)
                        .addComponent(jBEliminar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFBuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBModificar)
                    .addComponent(jBEliminar)
                    .addComponent(jBAgregar)
                    .addComponent(jBEjemplar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE))
        );

        jLAtras.setForeground(new java.awt.Color(0, 0, 255));
        jLAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        jLAtras.setText("Atras");
        jLAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLAtrasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLAtras)
                        .addGap(436, 436, 436)
                        .addComponent(jLabel6)
                        .addContainerGap(488, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLAtras)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        AgregarLibro al = new AgregarLibro();
        al.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBAgregarActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        try {
            ModificarLibro ml = new ModificarLibro(Integer.parseInt(tabla.selected(jTLibros)));
            ml.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un libro para modificar", "Error! No se puede modificar libro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        try {
            String f = tabla.selected(jTLibros);

            if (JOptionPane.showConfirmDialog(rootPane, "Se eliminará el libro seleccionado, ¿desea continuar?",
                    "Eliminar Registro", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                try {
                    ali.eliminarLibro(Integer.parseInt(tabla.selected(jTLibros)));
                    jTLibros.setModel(mostrarLibros());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Ha ocurrido un error \nPor favor intente de nuevo mas tarde ", "Ha ocurrido un error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un libro para eliminar", "Error! No se puede eliminar libro", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        this.jTLibros.setModel(buscarLibros(""));
        tabla.resizeColumnWidth(jTLibros);
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jTFBuscarLibroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFBuscarLibroKeyPressed
        this.jTLibros.setModel(buscarLibros(jTFBuscarLibro.getText()));
        tabla.resizeColumnWidth(jTLibros);
    }//GEN-LAST:event_jTFBuscarLibroKeyPressed

    private void jBEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEjemplarActionPerformed
        try {
            AgregarEjemplar ej = new AgregarEjemplar(Integer.parseInt(tabla.selected(jTLibros)));
            ej.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un libro para administrar sus ejemplares.", "Error! No se puede mostrar ventana de ejemplares", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBEjemplarActionPerformed

    private void jLAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAtrasMouseClicked
        Principal principal = new Principal();
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLAtrasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarLibros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEjemplar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JLabel jLAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFBuscarLibro;
    private javax.swing.JTable jTLibros;
    // End of variables declaration//GEN-END:variables
}
